[tox]
isolated_build = true
skipsdist=true
envlist = py{310,311,312}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
dependency_groups = dev
commands =
    pytest --cov-report term --cov=capgains tests/
